version: "2.1"
services:
  loadbalancer:
    image: marc0janssen/loadbalancer
    container_name: loadbalancer
    volumes:
      - /home/admin/docker/loadbalancer/config/etc/nginx:/etc/nginx
    ports:
      - 80:80
    restart: unless-stopped
    network_mode: bridge
    